# Generated by Django 4.2.5 on 2023-10-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En espera', 'En espera'), ('Adoptado', 'Adoptado')], default='Disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10)),
            ],
        ),
    ]
