# Generated by Django 4.2.5 on 2023-10-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pets'),
        ),
    ]
