# Generated by Django 4.2.5 on 2023-10-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0002_pet_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud_adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], max_length=20)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='formulario_voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], max_length=20)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
