# Generated by Django 4.2.5 on 2023-10-12 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0003_solicitud_adopcion_formulario_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], max_length=20)),
                ('disponibilidad_tiempo', models.CharField(help_text='¿Cuándo estás disponible para ser voluntario?', max_length=255)),
                ('experiencia_previa', models.TextField(help_text='Describe tu experiencia previa como voluntario o con mascotas.')),
                ('habilidades', models.TextField(help_text='¿Tienes habilidades específicas que puedan ser útiles como voluntario?')),
                ('por_que_voluntario', models.TextField(help_text='Explícanos por qué te gustaría ser voluntario.')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], max_length=20)),
                ('nombre_solicitante', models.CharField(max_length=50)),
                ('correo_solicitante', models.EmailField(max_length=254)),
                ('telefono_solicitante', models.CharField(max_length=10)),
                ('direccion_solicitante', models.TextField()),
                ('motivo_solicitud', models.TextField()),
                ('experiencia_mascotas', models.TextField()),
                ('otras_mascotas_en_casa', models.BooleanField()),
                ('espacio_en_casa', models.TextField()),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud_adopcion',
            name='id_mascota',
        ),
        migrations.RemoveField(
            model_name='solicitud_adopcion',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='formulario_voluntario',
        ),
        migrations.DeleteModel(
            name='solicitud_adopcion',
        ),
    ]
