# Generated by Django 4.2.5 on 2023-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_formulariovoluntario_solicitudadopcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariovoluntario',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], default='en_espera', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='estado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('en_espera', 'En espera'), ('denegado', 'Denegado')], default='en_espera', max_length=20),
        ),
    ]
